# -*- coding: utf-8 -*-
"""Copy of assignment 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13zY5SN8zAjS41GzLAJ7KTtBxzyPN7WLw
"""

# -*- coding: utf-8 -*-
"""Untitled8.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1cmZqPMJSkAO3VlPItN5L-AgUNfPe1o22
"""

# -*- coding: utf-8 -*-
"""Untitled18.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1ANoV7AhqUPwgpLl_aIF-6euL39uLdxmy
"""

import numpy as np
import matplotlib.pyplot as plt
import numpy.linalg as LA

plt.axis([-2,6,-4,8])

plt.xticks(np.arange(-2, 6, 1))
plt.yticks(np.arange(-4, 8, 1))

plt.axis('on')
plt.grid(True)

A = np.array([4,0])
B = np.array([0,4])
P = np.array([0,0])
Q = np.array([2,6])

def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB

  #Generating all lines
x_AB = line_gen(A,B)
x_PQ = line_gen(P,Q)

#Plotting all lines
plt.plot(x_AB[0,:],x_AB[1,:],label='$AB$')
plt.plot(x_PQ[0,:],x_PQ[1,:],label='$PQ$')

plt.text(0,0,'P(0,0)')
plt.text(2,6,'Q(2,6)')
plt.text(4,0,'A(4,0)')
plt.text(0,4,'B(0,4)')

plt.savefig('lines.pdf')
plt.show()